name: 自动预测

on:
  schedule:
    - cron: '*/3 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: 运行预测
        env:
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: node auto_predict.js
